spring:
  application:
    name: AutoPecas

  datasource:
    # TROQUE localhost por mysql_cp2
    url: jdbc:mysql://mysql_cp2:3306/checkpoint_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Dica: O Hibernate moderno já detecta o dialeto, 
        # mas manter o MySQL8Dialect está correto.
        dialect: org.hibernate.dialect.MySQL8Dialect
